apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rjac432-rjac432-poi-gateway-app-dev
  annotations:
    argocd/app-name: rjac432-rjac432-poi-gateway-app-dev
    backstage.io/kubernetes-id: rjac432-rjac432-poi-gateway-app-dev
    backstage.io/kubernetes-namespace: rjac432
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=rjac432-rjac432-poi-gateway-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus1/rjac432-gateway
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/rjac432/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/rjac432/deployments/rjac432-poi-gateway-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/rjac432-gateway?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/rjac432"
  system: workshop-system-rjac432
  providesApis:
    - gateway-api-rjac432
  consumesApis:
    - backend-api-rjac432
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-rjac432
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/rjac432"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gateway-api-rjac432
  description: API surface exposed to interact with Backends (summit POIs + parks data) via the Gateway
  links:
    - url: http://rjac432-poi-gateway-app-rjac432.apps.summit23rock.n26o.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/Summit23Janus1/rjac432-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/rjac432"
  system: workshop-system-rjac432
  definition:
    $text: https://github.com/Summit23Janus1/rjac432-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
